use_frameworks!

target 'ZWSEncryption_Example' do
  pod 'ZWSEncryption', :path => '../'

  target 'ZWSEncryption_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
